### ISSUE TITLE
Please support the browser platform as a development environment

### ISSUE THREAD

**Issue by jlchereau** [lynrin/cordova-plugin-buildinfo#14]
See https://moduscreate.com/blog/supporting-the-browser-platform-in-a-cordova-plugin/

**Comment by lynrin** [comment]
In v2.0.2, measures are taken against the browser platform.

At that time, since cordova-plugin-buildinfo can be run on the browser platform, I think that I can proceed with correspondence.

**Comment by lynrin** [comment]
v3.0.1 supports browser platform.
