### ISSUE TITLE
Build fails in PhoneGap Build (iOS)

### ISSUE THREAD

**Issue by blukis** [lynrin/cordova-plugin-buildinfo#21]
iOS build fails in PhoneGap Build when paired with plugin "cordova-universal-links-plugin-fix".  Fails with these in config.xml:
`<plugin name="cordova-plugin-buildinfo" />`
`<plugin name="cordova-universal-links-plugin-fix" />`

Previous version builds OK.
`<plugin name="cordova-plugin-buildinfo" version="2.0.3" />`
`<plugin name="cordova-universal-links-plugin-fix" />`

Note: while "cordova-universal-links-plugin-fix" plugin claims to be unmaintained, it's required in the official firebase-auth instructions:  https://firebase.google.com/docs/auth/web/cordova

**Comment by lynrin** [comment]
Thank you for your report.

I confirmed the symptoms.

With the addition of electron support, it seems that the plug-in is not working except for the latest Cordova.

Please wait for the revised version.

**Comment by lynrin** [comment]
Fixed in [v3.0.1](https://github.com/lynrin/cordova-plugin-buildinfo/releases/tag/v3.0.1).

Thank you for the report.
