### ISSUE TITLE
Error: exec proxy not found for :: BuildInfo :: init

### ISSUE THREAD

**Issue by KinSai1975** [lynrin/cordova-plugin-buildinfo#6]
Hi,

I have a problem initializing the plugin when loading by the emulator, I followed the installation procedure.
I have no more explanation, so I wonder why ??

**Comment by lynrin** [comment]
Please tell us a little more about the environment you are using cordova-plugin-buildinfo.

For example,
- Cordova version
- Version of the platform you are trying to use
- List of plugins
- etc...

**Comment by zlatkovtv** [comment]
Hello,

1. I ran into the same issue using The Phonegap Framework7 template and attempting to connect to Firebase. Firebase requires the cordova-plugin-buildinfo to be added.

2. So I did that, and when I run the app in the browser this appears in the google dev console:
Error: exec proxy not found for :: BuildInfo :: init
BuildInfo init fail
Missing Command Error

3. My setup:
Cordova 7.0.1
Android 6.2.3
Browser 4.1.0

4. Plugins:
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 1.1.0 "BuildInfo"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-statusbar 2.2.4-dev "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"

5. Can this be a situation where the plugin only works for the browser platform? It makes no sense to me as the Firebase Cordova guide for web requires it to be installed.

Please help :3

**Comment by travisdahl** [comment]
^ Exact same situation as above

**Comment by lynrin** [comment]
Thank you for plugin information etc.

I will try to reproduce it or try it.

**Comment by lynrin** [comment]
For versions other than Android, iOS, and Windows, we released version 2.0.2 that prevented cordova-plugin-buildinfo from running.
